package view;

import utils.GerenciadorJanelas;

public class TelaPrincipal extends javax.swing.JFrame {
    GerenciadorJanelas gerenciador; // Gerenciador das Janelas Internas
    
    // Construtor
    public TelaPrincipal() {
        initComponents();
        this.gerenciador = new GerenciadorJanelas(jdp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jmDados = new javax.swing.JMenu();
        jmiEditD = new javax.swing.JMenuItem();
        jmiViewD = new javax.swing.JMenuItem();
        jsD = new javax.swing.JPopupMenu.Separator();
        jmNewD = new javax.swing.JMenu();
        jmiNewF = new javax.swing.JMenuItem();
        jmiNewInfo = new javax.swing.JMenuItem();
        jmProfissional = new javax.swing.JMenu();
        jmiNewP = new javax.swing.JMenuItem();
        jmiEditP = new javax.swing.JMenuItem();
        jmiViewP = new javax.swing.JMenuItem();
        jmAtendimentos = new javax.swing.JMenu();
        jmExames = new javax.swing.JMenu();
        jmiNewE = new javax.swing.JMenuItem();
        jmiEditE = new javax.swing.JMenuItem();
        jmiViewE = new javax.swing.JMenuItem();
        jsA = new javax.swing.JPopupMenu.Separator();
        jmResultados = new javax.swing.JMenu();
        jmiNewR = new javax.swing.JMenuItem();
        jmiViewR = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISCOIMP - Sistema de Controle de Informações Médicas Pessoal");
        setResizable(false);

        javax.swing.GroupLayout jdpLayout = new javax.swing.GroupLayout(jdp);
        jdp.setLayout(jdpLayout);
        jdpLayout.setHorizontalGroup(
            jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jdpLayout.setVerticalGroup(
            jdpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        jmArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Arquivo_32px.png"))); // NOI18N
        jmArquivo.setText("Arquivo");
        jMenuBar1.add(jmArquivo);

        jmDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Pessoal_24px.png"))); // NOI18N
        jmDados.setText("Seus Dados");

        jmiEditD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Editar_24px.png"))); // NOI18N
        jmiEditD.setText("Editar");
        jmDados.add(jmiEditD);

        jmiViewD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/View_24px.png"))); // NOI18N
        jmiViewD.setText("Visualizar");
        jmDados.add(jmiViewD);
        jmDados.add(jsD);

        jmNewD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Novo_24px.png"))); // NOI18N
        jmNewD.setText("Adicionar");

        jmiNewF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Familiar_24px.png"))); // NOI18N
        jmiNewF.setText("Familiar");
        jmiNewF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewFActionPerformed(evt);
            }
        });
        jmNewD.add(jmiNewF);

        jmiNewInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Emergencia_24px.png"))); // NOI18N
        jmiNewInfo.setText("Informações de Emergência");
        jmiNewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewInfoActionPerformed(evt);
            }
        });
        jmNewD.add(jmiNewInfo);

        jmDados.add(jmNewD);

        jMenuBar1.add(jmDados);

        jmProfissional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Profissional_24px.png"))); // NOI18N
        jmProfissional.setText("Profissionais");

        jmiNewP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Novo_24px.png"))); // NOI18N
        jmiNewP.setText("Novo");
        jmiNewP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewPActionPerformed(evt);
            }
        });
        jmProfissional.add(jmiNewP);

        jmiEditP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Editar_24px.png"))); // NOI18N
        jmiEditP.setText("Editar");
        jmProfissional.add(jmiEditP);

        jmiViewP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/View_24px.png"))); // NOI18N
        jmiViewP.setText("Visualizar");
        jmProfissional.add(jmiViewP);

        jMenuBar1.add(jmProfissional);

        jmAtendimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Atendimento_24px.png"))); // NOI18N
        jmAtendimentos.setText("Atendimentos");

        jmExames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Agenda_24px.png"))); // NOI18N
        jmExames.setText("Consultas/Exames");

        jmiNewE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Novo_24px.png"))); // NOI18N
        jmiNewE.setText("Agendar");
        jmiNewE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewEActionPerformed(evt);
            }
        });
        jmExames.add(jmiNewE);

        jmiEditE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Editar_24px.png"))); // NOI18N
        jmiEditE.setText("Editar");
        jmExames.add(jmiEditE);

        jmiViewE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/View_24px.png"))); // NOI18N
        jmiViewE.setText("Visualizar");
        jmExames.add(jmiViewE);

        jmAtendimentos.add(jmExames);
        jmAtendimentos.add(jsA);

        jmResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Resultado_24px.png"))); // NOI18N
        jmResultados.setText("Resultados");

        jmiNewR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/NovoResultado_24px.png"))); // NOI18N
        jmiNewR.setText("Enviar");
        jmResultados.add(jmiNewR);

        jmiViewR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/View_24px.png"))); // NOI18N
        jmiViewR.setText("Visualizar");
        jmResultados.add(jmiViewR);

        jmAtendimentos.add(jmResultados);

        jMenuBar1.add(jmAtendimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNewFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewFActionPerformed
        // TODO add your handling code here:
        gerenciador.abrirJanela(TelaNewF.getInstancia());
    }//GEN-LAST:event_jmiNewFActionPerformed

    private void jmiNewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewInfoActionPerformed
        // TODO add your handling code here:
        TelaNewInfo telaNewInfo = TelaNewInfo.getInstancia();
        gerenciador.abrirJanela(TelaNewInfo.getInstancia());
    }//GEN-LAST:event_jmiNewInfoActionPerformed

    private void jmiNewPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewPActionPerformed
        // TODO add your handling code here:
        gerenciador.abrirJanela(TelaNewP.getInstancia());
    }//GEN-LAST:event_jmiNewPActionPerformed

    private void jmiNewEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewEActionPerformed
        // TODO add your handling code here:
        gerenciador.abrirJanela(TelaNewE.getInstancia());
    }//GEN-LAST:event_jmiNewEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdp;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmAtendimentos;
    private javax.swing.JMenu jmDados;
    private javax.swing.JMenu jmExames;
    private javax.swing.JMenu jmNewD;
    private javax.swing.JMenu jmProfissional;
    private javax.swing.JMenu jmResultados;
    private javax.swing.JMenuItem jmiEditD;
    private javax.swing.JMenuItem jmiEditE;
    private javax.swing.JMenuItem jmiEditP;
    private javax.swing.JMenuItem jmiNewE;
    private javax.swing.JMenuItem jmiNewF;
    private javax.swing.JMenuItem jmiNewInfo;
    private javax.swing.JMenuItem jmiNewP;
    private javax.swing.JMenuItem jmiNewR;
    private javax.swing.JMenuItem jmiViewD;
    private javax.swing.JMenuItem jmiViewE;
    private javax.swing.JMenuItem jmiViewP;
    private javax.swing.JMenuItem jmiViewR;
    private javax.swing.JPopupMenu.Separator jsA;
    private javax.swing.JPopupMenu.Separator jsD;
    // End of variables declaration//GEN-END:variables
}
